print(False or False or False or False or False or False or False or False)   # 00000000
print(False or False or False or False or False or False or False or True)    # 00000001
print(False or False or False or False or False or False or True or False)    # 00000010
print(False or False or False or False or False or False or True or True)     # 00000011
print(False or False or False or False or False or True or False or False)    # 00000100
print(False or False or False or False or False or True or False or True)     # 00000101
print(False or False or False or False or False or True or True or False)     # 00000110
print(False or False or False or False or False or True or True or True)      # 00000111
print(False or False or False or False or True or False or False or False)    # 00001000
print(False or False or False or False or True or False or False or True)     # 00001001
print(False or False or False or False or True or False or True or False)     # 00001010
print(False or False or False or False or True or False or True or True)      # 00001011
print(False or False or False or False or True or True or False or False)     # 00001100
print(False or False or False or False or True or True or False or True)      # 00001101
print(False or False or False or False or True or True or True or False)      # 00001110
print(False or False or False or False or True or True or True or True)       # 00001111
print(False or False or False or True or False or False or False or False)     # 00010000
print(False or False or False or True or False or False or False or True)      # 00010001
print(False or False or False or True or False or False or True or False)      # 00010010
print(False or False or False or True or False or False or True or True)       # 00010011
print(False or False or False or True or False or True or False or False)      # 00010100
print(False or False or False or True or False or True or False or True)       # 00010101
print(False or False or False or True or False or True or True or False)       # 00010110
print(False or False or False or True or False or True or True or True)        # 00010111
print(False or False or False or True or True or False or False or False)      # 00011000
print(False or False or False or True or True or False or False or True)       # 00011001
print(False or False or False or True or True or False or True or False)       # 00011010
print(False or False or False or True or True or False or True or True)        # 00011011
print(False or False or False or True or True or True or False or False)       # 00011100
print(False or False or False or True or True or True or False or True)        # 00011101
print(False or False or False or True or True or True or True or False)        # 00011110
print(False or False or False or True or True or True or True or True)         # 00011111
print(False or False or True or False or False or False or False or False)     # 00100000
print(False or False or True or False or False or False or False or True)      # 00100001
print(False or False or True or False or False or False or True or False)      # 00100010
print(False or False or True or False or False or False or True or True)       # 00100011
print(False or False or True or False or False or True or False or False)      # 00100100
print(False or False or True or False or False or True or False or True)       # 00100101
print(False or False or True or False or False or True or True or False)       # 00100110
print(False or False or True or False or False or True or True or True)        # 00100111
print(False or False or True or False or True or False or False or False)      # 00101000
print(False or False or True or False or True or False or False or True)       # 00101001
print(False or False or True or False or True or False or True or False)       # 00101010
print(False or False or True or False or True or False or True or True)        # 00101011
print(False or False or True or False or True or True or False or False)       # 00101100
print(False or False or True or False or True or True or False or True)        # 00101101
print(False or False or True or False or True or True or True or False)        # 00101110
print(False or False or True or False or True or True or True or True)         # 00101111
print(False or False or True or True or False or False or False or False)      # 00110000
print(False or False or True or True or False or False or False or True)       # 00110001
print(False or False or True or True or False or False or True or False)       # 00110010
print(False or False or True or True or False or False or True or True)        # 00110011
print(False or False or True or True or False or True or False or False)       # 00110100
print(False or False or True or True or False or True or False or True)        # 00110101
print(False or False or True or True or False or True or True or False)        # 00110110
print(False or False or True or True or False or True or True or True)         # 00110111
print(False or False or True or True or True or False or False or False)       # 00111000
print(False or False or True or True or True or False or False or True)        # 00111001
print(False or False or True or True or True or False or True or False)        # 00111010
print(False or False or True or True or True or False or True or True)         # 00111011
print(False or False or True or True or True or True or False or False)        # 00111100
print(False or False or True or True or True or True or False or True)         # 00111101
print(False or False or True or True or True or True or True or False)         # 00111110
print(False or False or True or True or True or True or True or True)          # 00111111
print(False or True or False or False or False or False or False or False)      # 01000000
print(False or True or False or False or False or False or False or True)       # 01000001
print(False or True or False or False or False or False or True or False)       # 01000010
print(False or True or False or False or False or False or True or True)        # 01000011
print(False or True or False or False or False or True or False or False)       # 01000100
print(False or True or False or False or False or True or False or True)        # 01000101
print(False or True or False or False or False or True or True or False)        # 01000110
print(False or True or False or False or False or True or True or True)         # 01000111
print(False or True or False or False or True or False or False or False)       # 01001000
print(False or True or False or False or True or False or False or True)        # 01001001
print(False or True or False or False or True or False or True or False)        # 01001010
print(False or True or False or False or True or False or True or True)         # 01001011
print(False or True or False or False or True or True or False or False)        # 01001100
print(False or True or False or False or True or True or False or True)         # 01001101
print(False or True or False or False or True or True or True or False)         # 01001110
print(False or True or False or False or True or True or True or True)          # 01001111
print(False or True or True or False or False or False or False or False)       # 01010000
print(False or True or True or False or False or False or False or True)        # 01010001
print(False or True or True or False or False or False or True or False)        # 01010010
print(False or True or True or False or False or False or True or True)         # 01010011
print(False or True or True or False or False or True or False or False)        # 01010100
print(False or True or True or False or False or True or False or True)         # 01010101
print(False or True or True or False or False or True or True or False)         # 01010110
print(False or True or True or False or False or True or True or True)          # 01010111
print(False or True or True or True or False or False or False or False)        # 01011000
print(False or True or True or True or False or False or False or True)         # 01011001
print(False or True or True or True or False or True or False or False)         # 01011010
print(False or True or True or True or False or True or True or True)           # 01011011
print(False or True or True or True or True or False or False or False)         # 01011100
print(False or True or True or True or True or False or False or True)          # 01011101
print(False or True or True or True or True or True or False or False)          # 01011110
print(False or True or True or True or True or True or True or True)            # 01011111