print(True or True or False or False or False or False or False or False)       # 10100000
print(True or True or False or False or False or False or False or True)        # 10100001
print(True or True or False or False or False or False or True or False)        # 10100010
print(True or True or False or False or False or False or True or True)         # 10100011
print(True or True or False or False or False or True or False or False)        # 10100100
print(True or True or False or False or False or True or False or True)         # 10100101
print(True or True or False or False or False or True or True or False)         # 10100110
print(True or True or False or False or False or True or True or True)          # 10100111
print(True or True or False or False or True or False or False or False)        # 10101000
print(True or True or False or False or True or False or False or True)         # 10101001
print(True or True or False or False or True or False or True or False)         # 10101010
print(True or True or False or False or True or False or True or True)          # 10101011
print(True or True or False or False or True or True or False or False)         # 10101100
print(True or True or False or False or True or True or False or True)          # 10101101
print(True or True or False or False or True or True or True or False)          # 10101110
print(True or True or False or False or True or True or True or True)           # 10101111
print(True or True or True or False or False or False or False or False)        # 10110000
print(True or True or True or False or False or False or False or True)         # 10110001
print(True or True or True or False or False or False or True or False)         # 10110010
print(True or True or True or False or False or False or True or True)          # 10110011
print(True or True or True or False or False or True or False or False)         # 10110100
print(True or True or True or False or False or True or False or True)          # 10110101
print(True or True or True or False or False or True or True or False)          # 10110110
print(True or True or True or False or False or True or True or True)           # 10110111
print(True or True or True or True or False or False or False or False)          # 10111000
print(True or True or True or True or False or False or False or True)           # 10111001
print(True or True or True or True or False or True or False or False)           # 10111010
print(True or True or True or True or False or True or True or True)            # 10111011
print(True or True or True or True or True or False or False or False)           # 10111100
print(True or True or True or True or True or False or False or True)            # 10111101
print(True or True or True or True or True or True or False or False)            # 10111110
print(True or True or True or True or True or True or True or True)             # 10111111