print(False or False or False or False or False or False or False or False)  # False
print(False or False or False or False or False or False or False or True)   # True
print(False or False or False or False or False or False or True or False)   # True
print(False or False or False or False or False or False or True or True)    # True
print(False or False or False or False or False or True or False or False)   # True
print(False or False or False or False or False or True or False or True)    # True
print(False or False or False or False or False or True or True or False)    # True
print(False or False or False or False or False or True or True or True)     # True
print(False or False or False or False or True or False or False or False)   # True
print(False or False or False or False or True or False or False or True)    # True
print(False or False or False or False or True or False or True or False)    # True
print(False or False or False or False or True or False or True or True)     # True
print(False or False or False or False or True or True or False or False)    # True
print(False or False or False or False or True or True or False or True)     # True
print(False or False or False or False or True or True or True or False)     # True
print(False or False or False or False or True or True or True or True)      # True
print(False or False or False or True or False or False or False or False)   # True
print(False or False or False or True or False or False or False or True)    # True
print(False or False or False or True or False or False or True or False)    # True
print(False or False or False or True or False or False or True or True)     # True
print(False or False or False or True or False or True or False or False)    # True
print(False or False or False or True or False or True or False or True)     # True
print(False or False or False or True or False or True or True or False)     # True
print(False or False or False or True or False or True or True or True)      # True
print(False or False or False or True or True or False or False or False)    # True
print(False or False or False or True or True or False or False or True)     # True
print(False or False or False or True or True or False or True or False)     # True
print(False or False or False or True or True or False or True or True)      # True
print(False or False or False or True or True or True or False or False)     # True
print(False or False or False or True or True or True or False or True)      # True
print(False or False or False or True or True or True or True or False)      # True
print(False or False or False or True or True or True or True or True)       # True
print(False or False or True or False or False or False or False or False)   # True
print(False or False or True or False or False or False or False or True)    # True
print(False or False or True or False or False or False or True or False)    # True
print(False or False or True or False or False or False or True or True)     # True
print(False or False or True or False or False or True or False or False)    # True
print(False or False or True or False or False or True or False or True)     # True
print(False or False or True or False or False or True or True or False)     # True
print(False or False or True or False or False or True or True or True)      # True
print(False or False or True or False or True or False or False or False)    # True
print(False or False or True or False or True or False or False or True)     # True
print(False or False or True or False or True or False or True or False)     # True
print(False or False or True or False or True or False or True or True)      # True
print(False or False or True or False or True or True or False or False)     # True
print(False or False or True or False or True or True or False or True)      # True
print(False or False or True or False or True or True or True or False)      # True
print(False or False or True or False or True or True or True or True)       # True
print(False or False or True or True or False or False or False or False)    # True
print(False or False or True or True or False or False or False or True)     # True
print(False or False or True or True or False or False or True or False)     # True
print(False or False or True or True or False or False or True or True)      # True
print(False or False or True or True or False or True or False or False)     # True
print(False or False or True or True or False or True or False or True)      # True
print(False or False or True or True or False or True or True or False)      # True
print(False or False or True or True or False or True or True or True)       # True
print(False or False or True or True or True or False or False or False)     # True
print(False or False or True or True or True or False or False or True)      # True
print(False or False or True or True or True or False or True or False)      # True
print(False or False or True or True or True or False or True or True)       # True
print(False or False or True or True or True or True or False or False)      # True
print(False or False or True or True or True or True or False or True)       # True
print(False or False or True or True or True or True or True or False)       # True
print(False or False or True or True or True or True or True or True)        # True